In [18]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
sale_data  = pd.read_csv("Sales_Data_Ecommerce.csv")
promotion_data = pd.read_excel("Promotion.csv.xlsx")

In [3]:
sale_data

,user_id,event_date,Day_of_Week,Channel,event_time,event_hour,event_timezone,event_type,product_id,category_id,category,sub_category1,sub_category2,brand,price,user_session,State,User_Score
0,21342,10/25/2019,Friday,Browser,14:11:00,14,UTC,View,18680,111,Electronics,smartphone,smartphone,Apple,64.33,8472453,WA,3
1,25649,10/18/2019,Friday,App,12:23:39,12,UTC,View,6100,180,Appliances,kitchen,refrigerators,Lg,489.96,1379135,CA,1
2,36102,11/26/2019,Tuesday,Browser,11:13:35,11,UTC,View,352,71,Electronics,smartphone,smartphone,Nokia,204.64,9666123,HI,1
3,38878,11/17/2019,Sunday,Browser,06:20:37,6,UTC,Purchase,10566,50,Electronics,audio,headphone,Apple,169.35,11408172,ND,1
4,47492,11/16/2019,Saturday,Browser,03:07:19,3,UTC,View,1924,115,Computers,notebook,notebook,Lenovo,851.59,3917052,MD,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159995,3982865,11/27/2019,Wednesday,App,17:50:49,17,UTC,View,564,71,Electronics,smartphone,smartphone,Huawei,163.88,3116480,IL,4
159996,4004840,11/28/2019,Thursday,App,16:22:25,16,UTC,View,2773,146,Computers,desktop,desktop,Lenovo,745.97,8173543,OR,1
159997,4018287,11/29/2019,Friday,App,08:11:46,8,UTC,View,915,71,Electronics,smartphone,smartphone,Xiaomi,196.13,7907717,CT,3
159998,4025333,11/29/2019,Friday,Browser,12:29:14,12,UTC,View,707,71,Electronics,smartphone,smartphone,Samsung,124.53,12629973,MI,1
159999,4027388,11/30/2019,Saturday,Browser,06:38:53,6,UTC,Cart,976,71,Electronics,smartphone,smartphone,Oppo,308.63,11229000,AK,3

a. What variables can be derived out of the data which can be helpful?

Here We derive variables such as average, median, mode, standard deviation, variance, correlation coefficient And  more depending on data 

b. Who can use this dashboard?

i can share this Dashboard  to  team members or stakeholders who interested in the insights that i  have derived from the data.

c. What value would be generated using this dashboard?

The value generated using this dashboard would depend on the insights that you have derived from the data. It could be anything from identifying trends to making informed decisions.
d. What additional data can be helpful to add more insights & value to the team?

Additional data such as demographic data, geographic data, psychographic data` can be helpful in adding more insights and value to the team.

In [24]:
price_vari_data= sale_data[['price','brand','category','Channel','event_time','event_type']]

In [28]:
price_vari_data

         price    brand     category  Channel event_time event_type
0        64.33    Apple  Electronics  Browser   14:11:00       View
1       489.96       Lg   Appliances      App   12:23:39       View
2       204.64    Nokia  Electronics  Browser   11:13:35       View
3       169.35    Apple  Electronics  Browser   06:20:37   Purchase
4       851.59   Lenovo    Computers  Browser   03:07:19       View
...        ...      ...          ...      ...        ...        ...
159995  163.88   Huawei  Electronics      App   17:50:49       View
159996  745.97   Lenovo    Computers      App   16:22:25       View
159997  196.13   Xiaomi  Electronics      App   08:11:46       View
159998  124.53  Samsung  Electronics  Browser   12:29:14       View
159999  308.63     Oppo  Electronics  Browser   06:38:53       Cart

[160000 rows x 6 columns]

1. Brand:
Different brands often have varying pricing strategies . Prices can vary widely between brands for similar products due to differences in quality, brand loyalty, and customer perception.

2. Category:
Prices can differ significantly across product categories due to factors such as production costs, supply and demand dynamics, and market competition. For example, electronic gadgets might have different price variations compared to groceries or fashion items.

3. Time:
Price variations over time can be influenced by factors. Prices might be higher during seasons or when a product is newly launched, and they may decrease as the product matures or during off-peak times.

4. Channel:
Price variations over channel so it can not influenced by factors

Traffic tends to be higher during weekdays (Monday to Friday) as people use the internet for work, education, and daily tasks. On weekends (Saturday and Sunday), traffic might decrease slightly as people engage in leisure activities.

Peak hours often coincide with regular daily routines, such as morning (8 AM to 10 AM) and late afternoon (2 PM to 4 PM) when people are more likely to be active online.

traffic might differ between browser and mobile devices. Mobile usage tends to peak during commuting hours and evenings, while browser usage might be higher during typical working hours.

High-level metrics are key performance indicators (KPIs) that provide a broad overview of a business's performance and growth. These metrics help measure the success of various aspects of the business, such as revenue generation, product performance, and market reach.
Revenue:

Definition: Total income generated from sales of products
Calculation: Sum of all sales transactions within a specific period (month, quarter, year).

Potential Revenue:

Definition: Estimated maximum achievable revenue based on market demand and ideal conversion rates.
Calculation: Potential Revenue = Total Addressable Market (TAM) * Conversion Rate.

Activity by brand or category is  the level of engagement, interactions, or transactions related to specific brands or product categories within a given timeframe. It involves measuring and analyzing customer actions, such as purchases, clicks, likes, shares, and comments, to understand the popularity and performance of different brands or categories

Search behavior refers to the way users search for information, products in our case  two specific search behaviors stand out: brand search by category and category search by brand.
Brand Search by Category:
This search behavior occurs for products  offered by a particular brand within a certain category  like apple or samsung
Category Search by Brand:
category search by brand happens with product category and want to explore different brands that offer products within that category. justlike  i our case many user want only smartphones they see  all smartphones with differt brands

The effects of special promotions  covers the positive and potential challenges associated with special promotions
as we seen in our data  when we give discounts promotion   so it effect the  sale   and increase the sale by good results

pricing fluctuations can impact customer acquisition and retention efforts as we see in our case

Lower prices might attract new customers, but if not managed well, these customers may leave once prices return to normal.
Fluctuating prices can lead to higher customer churn rates as customers seek out better deals.

Revenue by  every state